- name: Call dummy task and role from within this playbook
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Include the dummy task
      ansible.builtin.import_tasks: tasks/dummy.yml

    - name: Include the dummy role
      ansible.builtin.import_role:
        name: alnpir.dummy.dummy
      vars:
        dummy_hi_from: role within playbook

    - name: Run dummy module
      alnpir.dummy.dummy:
        name: "John Doe"
        changed: true
      register: dummy

    - name: Print dummy
      ansible.builtin.debug:
        var: dummy
